[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
regex = "1.10.5"
select = "0.6.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = "1.0.204"